### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by Nayels** [incentro-cloud/terraform-google-storage#1]
https://github.com/incentro-cloud/terraform-google-storage/blob/b59b4c64f7d24cba15f7b4657ea1dfd7cb5dd795/main.tf#L77

`x` is not explicit enough. Why not use ` for member in var.iam_members`

Same applies on https://github.com/incentro-cloud/terraform-google-storage/blob/b59b4c64f7d24cba15f7b4657ea1dfd7cb5dd795/main.tf#L56

**Comment by smorenburg** [comment]
Thanks for the feedback. Modified the naming, issue resolved.
